#!/usr/bin/python3
#SPDX-FileCopyrightText:2022 Ken Inaba rightman20020920@yahoo.co,jp
#SPDX-Licence-Identifire:BSD-3-Clause
#
import sys

ans=0 

for line in sys.stdin:
    line = line.rstrip()
    try:
        ans+=int(line)
    except:
        ans+=float(line)

print(ans)
