#!/usr/bin/python3
#SPDX-FileCopyrightText:2022 Ken Inaba rightman20020920@yahoo.co,jp
#SPDX-Licence-Identifire:BSD-3-Clause
#
import sys

ans=0 
ans2=1

for line in sys.stdin:
    line = line.rstrip()
    try:
        ans+=int(line)
    except:
        ans+=float(line)
    if(int(line)>0):
        try:
            ans2*=int(line)
        except:
            ans2*=float(line)

print("total")
print(ans)

print("total*")
print(ans2)


