#!/usr/bin/python3
#SPDX-FileCopyrightText:2022 Ken Inaba rightman20020920@yahoo.co,jp
#SPDX-Licence-Identifire:BSD-3-Clause
#
import sys

ans=0 
ans2=1

for line in sys.stdin:
    line = line.rstrip()
    if line == '一':
        line=1
    elif line == '二':
        line=2
    elif line == '三':
        line=3
    elif line== '四':
        line=4
    elif line=='五':
        line=5
    elif line=='六':
        line=6
    elif line=='七':
        line=7
    elif line=='八':
        line=8
    elif line=='九':
        line=9
    elif line=='十':
        line=10

    try:
        ans+=int(line)
    except:
        ans+=float(line)
    if(int(line)>0):
        try:
            ans2*=int(line)
        except:
            ans2*=float(line)

print("plus=",ans)
print("product=",ans2)



